### ISSUE TITLE
`--dry-run` not parsed the same as `-n`

### ISSUE THREAD

**Issue by twall** [peritus/bumpversion#129]
If I use `-n` the argument is parsed as a `part` (version 0.5.3).

`.bumpversion.cfg`:
```
[bumpversion]
current_version = 0.1.0
files = setup.py
commit = False
tag = False
tag_name = csf-google-{new_version}
parse = (?P<major>\d+)
        \.(?P<minor>\d+)
        \.(?P<patch>\d+)
        ((?P<release>[a-z]+)(?P<dev>\d+))?
serialize =
        {major}.{minor}.{patch}{release}{dev}
        {major}.{minor}.{patch}

[bumpversion:part:release]
optional_value = placeholder
first_value = dev
values =
        dev
        placeholder
```

**Comment by nehalecky** [comment]
I've also hit the same issue via `bumpversion -n --allow-dirty minor`:

```python
Traceback (most recent call last):
  File "/Users/nehalecky/miniconda2/envs/bombora/bin/bumpversion", line 11, in <module>
    sys.exit(main())
  File "/Users/nehalecky/miniconda2/envs/bombora/lib/python3.5/site-packages/bumpversion/__init__.py", line 912, in main
    f.should_contain_version(current_version, context)
  File "/Users/nehalecky/miniconda2/envs/bombora/lib/python3.5/site-packages/bumpversion/__init__.py", line 202, in should_contain_version
    if self.contains(serialized_version):
  File "/Users/nehalecky/miniconda2/envs/bombora/lib/python3.5/site-packages/bumpversion/__init__.py", line 214, in contains
    with io.open(self.path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'minor'
```

Running with `bumpversion --dry-run --allow-dirty minor` works just fine. :)

**Comment by michaelaye** [comment]
Same here, `-n` is not properly parsed, `--dry-run` is fine. Cost me half an hour to see what's going wrong. :(

**Comment by ulope** [comment]
I also ran into this today. Looking at the code it's not obvious why it should behave this way however the code is sufficiently complex (300+ lines of cli args and config file parsing) to not be easy to understand.

**Comment by ptim** [comment]
me too :) 

[sorry, still not sure which of these emojis signals a literal +1 (cos 👍  kinda implies 'nice work' / 'i like this')]

**Comment by michaelaye** [comment]
bump (the irony! ;)

**Comment by jobevers** [comment]
I think the error happens because https://github.com/peritus/bumpversion/blob/master/bumpversion/__init__.py#L509

Since `-n` obviously only has one dash, it is treated as a positional arg and is treated as the `part` of the version you want to change.

**Comment by gasparka** [comment]
Also lost some time because of this, looks like abandonware :(

**Comment by tsvi** [comment]
Same here. At least didn't spent more than an hour on this issue.

**Comment by dekoza** [comment]
This should be ported to `click` - it does much better work at parsing arguments.
