### ISSUE TITLE
Issues with using a config file with a specified part.

### ISSUE THREAD

**Issue by jackton1** [peritus/bumpversion#165]
My sample config file 
```cfg
[bumpversion]
current_version = 1.0.21
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
serialize = {major}.{minor}.{patch}
commit = True
tag = False
message = "{now:%Y-%m-%d %H:%M} - Increased version: {current_version} to {new_version}"

[bumpversion:part:patch]

[bumpversion:file:/path/to/setup.py]
search = version="{current_version}"
```
Raises
```python
Traceback (most recent call last):
  File "/usr/local/bin/bumpversion", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/bumpversion/__init__.py", line 912, in main
    f.should_contain_version(current_version, context)
  File "/Library/Python/2.7/site-packages/bumpversion/__init__.py", line 202, in should_contain_version
    if self.contains(serialized_version):
  File "/Library/Python/2.7/site-packages/bumpversion/__init__.py", line 214, in contains
    with io.open(self.path, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'patch'

```

**Comment by odoublewen** [comment]
I ran into this problem too, and found that `-n` and `--dry-run` are not equivalent, even though the usage message says they should be:
```
  --dry-run, -n         Don't write any files, just pretend. (default: False)
```

With `-n` I get the error your report.  With `--dry-run` it works as advertised.   @jackton1 - Which are you using?
