### ISSUE TITLE
bumpversion --help raise a UnicodeEncodeError #13

### ISSUE THREAD

**Issue by thanos** [peritus/bumpversion#177]
Using:

- Python 3.5.4 :: Continuum Analytics, Inc.
- Successfully installed bumpversion-0.5.3

Repeat of #13, not #18, #40, etc.

```
bumpversion --help
```
```python
> bumpversion --help
Traceback (most recent call last):
  File "c:\anaconda\envs\snsd\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda\envs\snsd\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\envs\snsd\Scripts\bumpversion.exe\__main__.py", line 9, in <module>
  File "c:\anaconda\envs\snsd\lib\site-packages\bumpversion\__init__.py", line 879, in main
    args = parser3.parse_args(remaining_argv + positionals)
  File "c:\anaconda\envs\snsd\lib\argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "c:\anaconda\envs\snsd\lib\argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "c:\anaconda\envs\snsd\lib\argparse.py", line 1964, in _parse_known_args
    start_index = consume_optional(start_index)
  File "c:\anaconda\envs\snsd\lib\argparse.py", line 1904, in consume_optional
    take_action(action, args, option_string)
  File "c:\anaconda\envs\snsd\lib\argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "c:\anaconda\envs\snsd\lib\argparse.py", line 1016, in __call__
    parser.print_help()
  File "c:\anaconda\envs\snsd\lib\argparse.py", line 2358, in print_help
    self._print_message(self.format_help(), file)
  File "c:\anaconda\envs\snsd\lib\argparse.py", line 2364, in _print_message
    file.write(message)
  File "c:\anaconda\envs\snsd\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 2437: character maps to <undefined>
```

**Comment by baasman** [comment]
Exact same error on my end.
