### ISSUE TITLE
changing file pointed to by a simlink

### ISSUE THREAD

**Issue by leventelist** [peritus/bumpversion#180]
I get this error message, when a file is changed by the

[bumpversion:file:simlink_file]

option:

fatal: pathspec 'some/file' is beyond a symbolic link
Traceback (most recent call last):
  File "/usr/bin/bumpversion", line 9, in <module>
    load_entry_point('bumpversion==0.5.3', 'console_scripts', 'bumpversion')()
  File "/usr/lib/python3/dist-packages/bumpversion/__init__.py", line 976, in main
    vcs.add_path(path)
  File "/usr/lib/python3/dist-packages/bumpversion/__init__.py", line 146, in add_path
    subprocess.check_output(["git", "add", "--update", path])
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'add', '--update', 'some/file']' returned non-zero exit status 128

I have bumpversion v0.5.3 (using Python v3.5.3)

**Comment by sharksforarms** [comment]
See this fork https://github.com/c4urself/bump2version/
