### ISSUE TITLE
Bumpversion --list returned non-zero exit status 1

### ISSUE THREAD

**Issue by rickstaa** [peritus/bumpversion#207]
When I try to check the current version using the `--list` argument I get the following output:

```
Traceback (most recent call last):
  File "/home/rstaa/.local/bin/bumpversion", line 11, in <module>
    sys.exit(main())
  File "/home/rstaa/.local/lib/python2.7/site-packages/bumpversion/__init__.py", line 994, in main
    vcs.commit(message=commit_message)
  File "/home/rstaa/.local/lib/python2.7/site-packages/bumpversion/__init__.py", line 73, in commit
    list(os.environ.items()) + [(b'HGENCODING', b'utf-8')]
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'git', u'commit', u'-F', '/tmp/tmpsD3hix']' returned non-zero exit status 1
```

Not to big of a deal since it still gives me the current version but just a heads up.

**Comment by rickstaa** [comment]
Closed due to inactivity.
